export const enum SAZONALIDADE_ACTION_TYPES  {
  FETCH_SAZONALIDADE_START = 'sazonalidade/FETCH_SAZONALIDADE_START',
  FETCH_SAZONALIDADE_SUCCESS = 'sazonalidade/FETCH_SAZONALIDADE_SUCCESS',
  FETCH_SAZONALIDADE_FAILED = 'sazonalidade/FETCH_SAZONALIDADE_FAILED',
  DELETE_SAZONALIDADES_START = 'sazonalidades/DELETE_SAZONALIDADES_START',
  DELETE_SAZONALIDADES_SUCCESS = 'sazonalidades/DELETE_SAZONALIDADES_SUCCESS',
  DELETE_SAZONALIDADES_FAILED = 'sazonalidades/DELETE_SAZONALIDADES_FAILED'
};

