export const enum SAZONALIDADE_ACTION_TYPES  {
  FETCH_SAZONALIDADE_START = 'sazonalidade/FETCH_SAZONALIDADE_START',
  FETCH_SAZONALIDADE_SUCCESS = 'sazonalidade/FETCH_SAZONALIDADE_SUCCESS',
  FETCH_SAZONALIDADE_FAILED = 'sazonalidade/FETCH_SAZONALIDADE_FAILED'
};

